apiVersion: v1
kind: Service
metadata:
  name: certchain-query
  namespace: certchain
spec:
  selector:
    app: certchain
  ports:
  - name: http
    port: 9879
    targetPort: 9879
    protocol: TCP
